### ISSUE TITLE
Crash when riding away from my base in a mine cart

### ISSUE THREAD

**Issue by Belgabor** [TeamCoS/Modular-Systems#103]
Client side crash in SMP. Probably not chunk-loading related, I shouldn't have been far enough away to unload the chunk.

```
---- Minecraft Crash Report ----
The pack has been tampered with. Do not report any errors.
 ChunkAnimator
 
// I'm sorry, Dave.
 
Time: 10/6/15 3:11 AM
Description: Ticking block entity
 
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to com.pauljoda.modularsystems.storage.blocks.BlockStorageIO
        at com.pauljoda.modularsystems.storage.tiles.TileStorageIO.func_145845_h(TileStorageIO.java:212)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full report: http://pastebin.com/TcMLqZ0P

**Comment by Belgabor** [comment]
Had this a couple of times more, now even when just travelling away from base. Definitely not chunk-loading related, friend was back at base when it happened.

**Comment by pauljoda** [comment]
Seems to be some casting issue. Not sure why but these things happen. Can't test for everything. I'll look into it if I have any free time
