### ISSUE TITLE
Mod Unusable - Render Crash

### ISSUE THREAD

**Issue by Sir-Will** [TeamCoS/Modular-Systems#109]
hey,
the mod is currently unusable as the chance to get the crash I posted below is very high.

Placing a crapenters block near Modular Storage Core = crash
Placing a sorting chest near Modular Storage Core = crash
Placing Crafting Storage Expansion in the world = crash

```
java.lang.IllegalArgumentException
	at java.util.PriorityQueue.<init>(Unknown Source)
	at net.minecraft.client.renderer.Tessellator.func_147564_a(Tessellator.java:160)
	at net.minecraft.client.renderer.WorldRenderer.func_147891_a(WorldRenderer.java:248)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:204)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.PriorityQueue.<init>(Unknown Source)
	at net.minecraft.client.renderer.Tessellator.func_147564_a(Tessellator.java:160)
	at net.minecraft.client.renderer.WorldRenderer.func_147891_a(WorldRenderer.java:248)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:204)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
```

**Comment by pauljoda** [comment]
This has recently popped up. It seems there may be a forge version issue. I'll have to look into it soon. Thanks for the report

**Comment by SirWilli** [comment]
So, still no update? Seems that i have to remove this mod.
