### ISSUE TITLE
[1.9] Always place the storage core first

### ISSUE THREAD

**Issue by Arttie** [TeamCoS/Modular-Systems#116]
If you forget to make a storage core and already have a pretty well built structure... don't do what I did and place the core last.... this happens.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (Quark-beta-5.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 3/31/16 11:31 PM
Description: Ticking player

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, east, south, west]} to down on block modularsystems:storageCore, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:208)
	at com.teambr.modularsystems.storage.blocks.BlockStorageCore.func_176203_a(BlockStorageCore.java:100)
	at biomesoplenty.common.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_AchievementEventHandler_onItemPickup_ItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerItemPickupEvent(FMLCommonHandler.java:572)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:392)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:565)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:557)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1962)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:301)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:286)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:208)
	at com.teambr.modularsystems.storage.blocks.BlockStorageCore.func_176203_a(BlockStorageCore.java:100)
	at biomesoplenty.common.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_AchievementEventHandler_onItemPickup_ItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerItemPickupEvent(FMLCommonHandler.java:572)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:392)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:565)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:557)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1962)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 126
	Entity Name: Arttie
	Entity's Exact location: 174.56, 64.00, 30.99
	Entity's Block location: World: (174,64,30), Chunk: (at 14,4,14 in 10,1; contains blocks 160,0,16 to 175,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:301)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:286)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@24be670e
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 144586104 bytes (137 MB) / 586153984 bytes (559 MB) up to 1029177344 bytes (981 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128M -Xmx1G -Xmn128M
	IntCache: cache: 0, tcache: 29, allocated: 1, tallocated: 67
	FML: MCP 9.23 Powered by Forge 12.16.0.1811 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1811-1.9.jar) 
	UCHIJAAAA	Forge{12.16.0.1811} [Minecraft Forge] (forge-1.9-12.16.0.1811-1.9.jar) 
	UCHIJAAAA	Baubles{1.2.0.0} [Baubles] (Baubles-1.9-1.2.0.0.jar) 
	UCHIJAAAA	BiomesOPlenty{4.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.0.1973-universal.jar) 
	UCHIJAAAA	bookshelfapi{3.0.3} [Bookshelf] (Bookshelf-API-1.9-3.0.3.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UCHIJAAAA	gravestone{1.2.2} [Gravestone] (Gravestone Mod 1.2.2.jar) 
	UCHIJAAAA	JEI{3.1.2.172} [Just Enough Items] (jei_1.9-3.1.2.172.jar) 
	UCHIJAAAA	matmod{2.0.1} [More Armor and Tools Mod] (matmod-2.0.1.jar) 
	UCHIJAAAA	modularsystems{3.0.0} [Modular Systems] (ModularSystems-1.9-3.0.0-B34.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-5.jar) 
	UCHIJAAAA	samsapples{1.1.5} [Power Apples] (PowerApples-1.9-1.1.5.jar) 
	UCHIJAAAA	Quark{beta-5} [Quark] (Quark-beta-5.jar) 
	UCHIJAAAA	survivalist{1.4.2} [Survivalist] (Survivalist-1.4.2.jar) 
	UCHIJAAAA	trashslot{3.0.4} [TrashSlot] (trashslot-mc1.9-3.0.4.jar) 
	UCHIJAAAA	VeinMiner{0.31.5_build.forgePost18010} [Vein Miner] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UCHIJAAAA	XaeroMinimap{1.8.5.2} [Xaero's Minimap] (Xaeros_Minimap_1.8.5.2_Forge_1.9.jar) 
	Loaded coremods (and transformers): 
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (Quark-beta-5.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Arttie'/126, l='Aviroum', x=174.56, y=64.00, z=30.99]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
````

**Comment by pauljoda** [comment]
This is actually a bug with biomes o plenty. I've talked with their dev about it already but I'll out in extra checks just in case
