### ISSUE TITLE
[1.9] [ModularSystems-1.9-3.0.2] [Forge 1865] Crash on launch with newest forge

### ISSUE THREAD

**Issue by Kazzamkablam** [TeamCoS/Modular-Systems#122]
Yeah this happened when I upgraded Forge:

java.lang.IllegalArgumentException: Duplicate id: proxy
	at net.minecraft.tileentity.TileEntity.func_145826_a(TileEntity.java:36)
	at net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:253)
	at com.teambr.modularsystems.core.managers.BlockManager$.registerBlock(BlockManager.scala:83)
	at com.teambr.modularsystems.core.managers.BlockManager$.registerBlock(BlockManager.scala:96)
	at com.teambr.modularsystems.core.managers.BlockManager$.preInit(BlockManager.scala:51)
	at com.teambr.modularsystems.core.ModularSystems$.preInit(ModularSystems.scala:60)
	at com.teambr.modularsystems.core.ModularSystems.preInit(ModularSystems.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:240)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by LlubNek** [comment]
Got this too.  Here's a crash report.
[crash-2016-04-23_21.46.35-client.txt](https://github.com/TeamCoS/Modular-Systems/files/233244/crash-2016-04-23_21.46.35-client.txt)
[fml-client-latest.log.txt](https://github.com/TeamCoS/Modular-Systems/files/233245/fml-client-latest.log.txt)

**Comment by DanWehr** [comment]
LlubNek's crash may also be a conflict with Integrated Dynamics ( #123 ), rather than updating forge, as that mod is also present in their crash report.

**Comment by Rongmario** [comment]
Disable the proxy block in IntDyn's config and the game should be able to run.

**Comment by Winddbourne** [comment]
I didn't have integrated dynamics in my file when the mod crashed though I was considering adding it in today. Do you have any idea what was going on with my crash?
