### ISSUE TITLE
Crash on Breaking Furnace Core

### ISSUE THREAD

**Issue by RaiderofRamen** [TeamCoS/Modular-Systems#63]
So, my the following crash occurred when I broke the furnace core of a completed cuboid, after I had added a liquid fuel power bank. It didn't crash before I had added the power bank, and from the crash report, my best guess is that the power bank tile is checking for the core, but it wasn't there.

Full crash report:
Description: Exception while updating neighbours

java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to com.teambr.bookshelf.common.blocks.BaseBlock
	at com.pauljoda.modularsystems.core.tiles.AbstractCore.getCorners(AbstractCore.java:216)
	at com.pauljoda.modularsystems.core.tiles.AbstractCore.isWellFormed(AbstractCore.java:112)
	at com.pauljoda.modularsystems.core.tiles.DummyTile.validateCore(DummyTile.java:206)
	at com.pauljoda.modularsystems.core.blocks.BlockDummy.func_149695_a(BlockDummy.java:87)
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:648)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
	at net.minecraft.world.World.func_147465_d(World.java:466)
	at net.minecraft.world.World.func_147449_b(World.java:600)
	at com.pauljoda.modularsystems.core.tiles.AbstractCore.deconstructMultiblock(AbstractCore.java:204)
	at com.pauljoda.modularsystems.core.tiles.AbstractCore.breakMultiBlock(AbstractCore.java:178)
	at com.pauljoda.modularsystems.furnace.blocks.BlockFurnaceCore.func_149749_a(BlockFurnaceCore.java:106)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1335)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:296)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.pauljoda.modularsystems.core.tiles.AbstractCore.getCorners(AbstractCore.java:216)
	at com.pauljoda.modularsystems.core.tiles.AbstractCore.isWellFormed(AbstractCore.java:112)
	at com.pauljoda.modularsystems.core.tiles.DummyTile.validateCore(DummyTile.java:206)
	at com.pauljoda.modularsystems.core.blocks.BlockDummy.func_149695_a(BlockDummy.java:87)

-- Block being updated --
Details:
	Source block type: ID #1496 (tile.modularsystems:dummy // com.pauljoda.modularsystems.core.blocks.BlockDummy)
	Block type: ID #1496 (tile.modularsystems:dummy // com.pauljoda.modularsystems.core.blocks.BlockDummy)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-570,80,1432), Chunk: (at 6,5,8 in -36,89; contains blocks -576,0,1424 to -561,255,1439), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
Stacktrace:
	at net.minecraft.world.World.func_147460_e(World.java:697)
	at net.minecraft.world.World.func_147459_d(World.java:648)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
	at net.minecraft.world.World.func_147465_d(World.java:466)
	at net.minecraft.world.World.func_147449_b(World.java:600)
	at com.pauljoda.modularsystems.core.tiles.AbstractCore.deconstructMultiblock(AbstractCore.java:204)
	at com.pauljoda.modularsystems.core.tiles.AbstractCore.breakMultiBlock(AbstractCore.java:178)
	at com.pauljoda.modularsystems.furnace.blocks.BlockFurnaceCore.func_149749_a(BlockFurnaceCore.java:106)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1335)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:296)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@47abe485
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by pauljoda** [comment]
Fixed for next release
