### ISSUE TITLE
Crash on Opening Solid Fuel Power Bank Interface

### ISSUE THREAD

**Issue by RaiderofRamen** [TeamCoS/Modular-Systems#64]
When I opened the solid fuel power bank while trying to put some blocks of coal inside, I crashed with the following report:

Description: Ticking memory connection

java.lang.IndexOutOfBoundsException: Index: 62, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:206)
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:206)
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@30a5ea9c
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Dyonovan** [comment]
Ok I can't seem to replicate this at this time, but with all the fixes we have just done it might have been fixed then. Going to push a new release any min with the changes. Closing for now, re-open if it is still happening after you update.
